ElasticSearchProject/elasticsearch

- client/src/router.js
- client/src/routes/Movie.js
> feat : movie page 구현

- client/src/router.js
- client/src/routes/Search.js
> feat : Search Page 구현

- client/src/components/main/HomeCard.js
- client/src/routes/Home.js
> main page 영화 card 레이아웃  구성ing

- client/src/components/search/Genre.js
- client/src/routes/Home.js
- client/src/routes/Search.js
Search Page header 특정 영화 검색 결과 , 장르 필터 버튼 , 정렬 버튼 레이아웃 구현
> feat : Search Page header 구현

- client/package-lock.json
- client/package.json
- client/src/components/search/Carousel.js
- client/src/components/search/NextArrow.js
- client/src/components/search/PrevArrow.js
- client/src/routes/Search.js
Search Page 상단 두 줄 캐루셀 레이아웃 구현
> feat : Search Page 상단 캐루셀 구현

- client/src/components/search/SearchItem.js
- client/src/components/search/SearchList.js
- client/src/routes/Search.js
Search Page 하단 SearchList 레이아웃 구현
> feat : Search Page SearchList 구현

- client/src/components/search/SortBox.js
- client/src/routes/Search.js
> refactor : 영화 정렬 컴포넌트 리팩토링

- client/src/components/search/SortBox.js
- client/src/routes/Home.js
- client/src/routes/Search.js
캐루셀 한 줄로 수정 , sortBox 위치 캐루셀 아래로 변경
> feat : Search Page 레이아웃 변경

- client/src/components/search/FloatingButton.js
- client/src/routes/Search.js
> feat : Search Page 업 버튼 구현

- client/src/components/main/CardArea.js
- client/src/components/main/HomeCard.js
- client/src/routes/Home.js
한 페이지 안에 영화 10개 한 눈에 볼 수 있도록 정렬 및 크기 조정 & <Link>걸어둠
> Main Page Card 정렬 및 크기 조정

- client/src/components/search/FloatingGenre.js
- client/src/routes/Search.js
Search Page 우측 장르 필터 스크롤 내리면 나오도록 구현
> feat : Search Page 우측 장르 필터 구현

- client/src/components/search/FloatingButton.js
> style : 업 버튼 색상 변경

- client/src/components/search/Carousel.js
- client/src/components/search/FloatingGenre.js
- client/src/components/search/Genre.js
- client/src/components/search/SearchItem.js
- client/src/components/search/SearchList.js
- client/src/components/search/SortBox.js
- client/src/routes/Search.js
> feat : Search Page 반응형 레이아웃 구현

- client/src/components/search/FloatingGenre.js
Floating Genre 필터 반응형 레이아웃 구현 완료
> feat : Floating Genre 필터 반응형

- client/src/components/common/Layout.js
- client/src/routes/Search.js
공통 레이아웃 react children을 받도록 코드 수정 & Search Page 적용
> feat : 공통 레이아웃 수정

- client/src/components/common/Layout.js
- client/src/globalStyle.js
> feat : 공통 레이아웃 홈 버튼 수정

- client/src/components/main/SearchInput.js
> style : 공통 레이아웃 검색 창 스타일 수정

- client/src/routes/Search.js
Search Page movie data 요청 기능 구현
> feat : Search Page movie data 요청 구현

- client/src/components/main/SearchInput.js
- client/src/components/search/SortBox.js
- client/src/routes/Search.js
> feat : 프론트 search 쿼리 변경

- client/src/components/search/FloatingGenre.js
- client/src/components/search/Genre.js
- client/src/routes/Search.js
- server/src/routes/search.js
- server/src/services/mainSearchService.js
Floating Genre 1 column으로 스타일 변경
> style : FloatingGenre 스타일 수정

- client/src/components/search/FloatingGenre.js
- client/src/components/search/SearchItem.js
- client/src/components/search/SearchList.js
- client/src/routes/Search.js
> feat : Search Page 데이터 렌더링

- server/src/services/mainSearchService.js
> feat : server Search Router 코드 변경

- client/src/components/search/SearchItem.js
> fix : Search Page 영화 이미지 수정

- client/src/components/search/SortBox.js
- client/src/routes/Search.js
SortBox 해당 정렬 기준 클릭 시 글자색 들어오게 수정 & 국가 별 sort는 필터방식으로 변경 예정
> feat : SortBox 클릭시 글씨 색 변경

- client/src/components/search/NationButton.js
> feat : 영화 국가 드롭다운 필터

- client/src/components/search/NationButton.js
- client/src/components/search/SortBox.js
- client/src/routes/Search.js
Sort 최신순 , 평점순 구현완료 & 국내 해외 영화  구현 완료
> feat : Search Page sort , 나라 필터 구현 완료

- client/src/components/search/SortBox.js
최신순 , 평점순 클릭했을 때 url 변경 되지 않는 문제 해결
> fix : 최신순 & 평점순 정렬 변경 안되는 문제

- server/src/services/mainSearchService.js
genreFilter = null 일 때 다른 필터 적용 안되는 문제 해결
> fix : genreFilter 문제 픽스

- client/src/components/search/Genre.js
- client/src/components/search/GenreButton.js
- client/src/components/search/NationButton.js
- client/src/routes/Search.js
Search Page 상단 장르 필터 기능 구현 & 중복 필터링 가능
> feat : Search Page 상단 장르 필터 기능 구현

- client/src/components/search/NationButton.js
- client/src/components/search/ShowTime.js
- client/src/components/search/SortBox.js
- client/src/routes/Search.js
Search Page 영화 러닝타임 슬라이더 필터 구현 & 슬라이딩에 따른 url 변경 완료
> feat : 영화 러닝타임 필터 구현

- client/src/components/search/GenreButton.js
- client/src/components/search/ShowTime.js
영화 상영시간 필터 Range Slider 로 수정 , genre 버튼 누를 때 영화 상영시간 필터 적용되도록 변경
> feat : Search Page 영화 상영시간 필터 수정

- client/src/components/search/FloatingGenre.js
- client/src/components/search/ShowTime.js
> style : 좌측 장르 필터 , 영화 상영시간 필터 위치 수정

- server/src/services/mainSearchService.js
- server/src/static/commonStatic.js
showTimeFilter 오타 수정 & index 명 변경
> fix : mainSearchService 오타 수정 & index 명 변경

- client/src/components/search/FloatingGenre.js
- client/src/components/search/Genre.js
- client/src/components/search/GenreButton.js
- client/src/routes/Search.js
좌측 FloatingGenre 필터와 상단 장르 필터와 상태 공유하도록 기능 수정
> feat : FloatingGenre 필터 상단 필터와 상태 동기화

- client/src/routes/Search.js
새로 고침 해도 클릭한 장르 버튼 변경되지 않도록 수정
> fix : 새로 고침 할 때 장르 버튼 유지되도록 수정

- client/package-lock.json
- client/package.json
- client/src/components/search/FloatingGenre.js
- client/src/components/search/Genre.js
- client/src/components/search/GenreButton.js
- client/src/components/search/MovieDateFilter.js
- client/src/components/search/RadioControlItem.js
- client/src/components/search/ShowTime.js
- client/src/routes/Search.js
개봉 날짜 필터 기능 구현 , 1개월 3개월 5개월 전체 영화로 필터링
> feat : 개봉 날짜 기능 구현

- client/src/components/search/FloatingGenre.js
- client/src/components/search/MovieDateFilter.js
- client/src/components/search/ShowTime.js
- client/src/routes/Search.js
장르 , 영화 상영시간, 영화 개봉 날짜 필터 레이아웃 위치 수정
> style : 필터 박스 위치 수정

- server/src/services/movieSearchService.js
- server/src/services/moviewReviewSearchService.js
> style : service 코드 공백 제거

- client/src/components/search/Carousel.js
> feat : Carousel hover 애니메이션

- client/src/components/search/Carousel.js
> style : Carousel 이미지 가로 길이 변경

- client/package-lock.json
- client/package.json
- client/src/components/main/SearchInput.js
- client/src/components/search/SortBox.js
- client/src/routes/Search.js
Search Page 무한 스크롤링 기능 구현 & sort 필터 클릭했을 때 무한 스크롤링 적용
> feat : Search Page 무한 스크롤링 구현 & sort 필터 무한 스크롤링 적용

- client/src/components/search/FloatingGenre.js
- client/src/components/search/Genre.js
- client/src/components/search/GenreButton.js
- client/src/routes/Search.js
> feat : Genre 필터 무한 스크롤 구현

- client/src/components/search/GenreSkeleton.js
- client/src/components/search/SearchSkeleton.js
- client/src/routes/Search.js
Genre 버튼 , Search Item 로딩 스켈레톤 추가
> feat : Search Page 로딩 스켈레톤 추가

- client/src/components/movie/Imagebox.js
- client/src/components/movie/Infobox.js
- client/src/components/movie/Infotable.js
- client/src/components/movie/Posterimage.js
- client/src/components/search/SearchItem.js
- client/src/routes/Movie.js
- client/src/styles/theme.js
movie detail page 상단 이미지 , info 박스 반응형 구현 완료 , 데이터 렌더링 출연 배우까지 완료
> feat : Movie detail page Header 반응형 & 출연 배우 데이터 렌더링

- client/src/components/movie/ModalMovie.js
모달에 마우스 hover 하면 영화 제목 나오도록 구현
> feat : 모달 이미지 hover 애니메이션 구현

- client/src/components/main/SearchInput.js
- client/src/components/movie/ModalMovie.js
- client/src/routes/Home.js
> feat : 검색창 자동완성 기능 구현

- client/src/components/main/SearchInput.js
현재 검색어 자동완성 리스트 상단에 추가 , 선택한 자동완성 단어 검색창에 렌더링 구현
> feat : 검색 자동완성 기능 구현

- client/src/components/common/AutoItem.js
- client/src/components/main/SearchInput.js
검색어 자동완성 포스터 , 영화 이름 , 영화 영어이름 구현, 자동완성 데이터 6개씩으로 변경
>  feat : 검색어 자동완성 리스트 구현

- client/src/components/common/Layout.js
- client/src/components/common/SearchInput.js
- client/src/routes/Home.js
- client/src/routes/Movie.js
- client/src/routes/Search.js
검색 자동완성 선택한 검색어가 검색창에 반영되도록 구현 , 자동완성 영화 클릭 시 detail page로 이동, 메인 로고 수정
> feat : 검색 자동완성 기능 구현 & 메인 페이지 로고 변경

- client/src/components/common/AutoItem.js
- client/src/components/common/SearchInput.js
- client/src/hooks/highlightedText.js
검색어 자동완성 영화 제목중 검색어 하이라이팅 기능 구현
> feat : 검색 자동완성 하이라이팅 구현

- client/src/components/common/SearchInput.js
> fix : nav 바 검색창 버그 픽스

- client/src/components/common/SearchInput.js
movie 페이지에서 자동완성 영화 리스트 검색 시 movie_id로 검색하는 오류 fix
> fix : movie 페이지에서 영화 검색 버그 fix

- client/src/components/movie/ClassifyButton.js
- client/src/components/movie/InfoBox.js
- client/src/components/movie/ReviewBox.js
- client/src/components/movie/ReviewSkeleton.js
- client/src/components/movie/ReviewTable.js
- client/src/routes/Movie.js
리뷰 무한 스크롤 구현하고 싶었으나 하다가 잘 되지 않아 멈췄습니다..
> movie page 리뷰 및 버튼 위치 조정 (반응형 반영)

- client/src/hooks/createRex.js
- client/src/hooks/highlightedText.js
자동완성 영화 제목과 검색어간 일치하는 부분을 영화 제목 앞쪽부터 하이라이팅 할 수 있도록 구현완료
> feat : 검색어 자동완성 하이라이팅 구현

- client/src/components/movie/ImageBox.js
- client/src/components/movie/InfoBox.js
- client/src/components/movie/InfoTable.js
- client/src/components/movie/PosterImage.js
movie page 영화 상세 설명 부분 레이아웃 수정
> style : movie info 레이아웃 수정

- client/src/components/common/SearchInput.js
상세페이지에서 배우, 감독 모달 영화 클릭시 클릭한 영화로 이동하지 않는 문제 수정
> fix : 상세페이지에서 모달 영화 클릭시 발생하는 오류 수정

- client/src/components/common/Carousel.js
- client/src/components/main/GenreCarousel.js
- client/src/components/search/MovieDateFilter.js
- client/src/components/search/ShowTime.js
- client/src/routes/Search.js
영화 시간 필터 , 영화 개봉날짜 필터 화면 크기 줄이면 레이아웃 망가지는 현상 fix
> fix : 화면 줄이면 레이아웃 깨지는 현상 fix

- client/src/routes/Search.js
검색 최초 시도 시 localstorage 에 캐루셀 데이터가 들어가지 않는 오류 fix
> fix : search page 상단 캐루셀 오류 fix

- client/src/components/movie/WordCloudBox.js
- client/src/components/movie/WordCloudCanvas.js
- client/src/routes/Movie.js
> style : wordcloud 레이아웃 수정

- client/src/components/movie/ImageBox.js
> feat : movie page 이미지 없음 처리

- client/src/components/movie/ImageBox.js
- client/src/components/movie/InfoBox.js
- client/src/components/movie/InfoTable.js
- client/src/components/movie/PosterImage.js
- client/src/routes/Movie.js
movie page 영화 정보 레이아웃 화면 크기에 따라 크기 유지하도록 변경 , 포스터 이미지 로딩처리
> style : movie page 영화 정보 수정 , 포스터 이미지 로딩처리

- client/src/components/movie/MultiReview.js
- client/src/components/movie/MultiReviewItem.js
- client/src/components/movie/ReviewTable.js
Review Table 긍정, 부정 소제목 , 각각 리뷰 구역 별로 스크롤링 구현
> feat : Review table 제목 , 스크롤창 구현
